app/controllers/recipe_controller.rb, config/routes.rb, test/controllers/recipe_controller_test.rb
楽天APIの設定をプライベート関数 rakuten_api で行うように変更
テストとして "should get pickup via rakuten api" を追加
=> レシピ表示用にコントローラーを修正

app/views/recipe/shopping_list.html.erb
=> Add shopping list view

app/controllers/recipe_controller.rb, app/views/recipe/shopping_list.html.erb, config/routes.rb
route に /shopping_list を追加しました。
controller に /shopping_list を追加しました。
=> Add route for shopping list

test/controllers/top_controller_test.rb
トップページが取得できる、というテストコードを追加しました。
参考：
https://github.com/tnumata3632/RakuTabi/blob/master/test/controllers/top_controller_test.rb
=> Add top#index test code

app/views/recipe/shopping_list.html.erb
=> デザインを調整しました

test/controllers/recipe_controller_test.rb
=> ない箇所のテストコードを補完していきます。

app/views/recipe/shopping_list.html.erb
=> shopping_list.html.erbのdivタグはtdタグの中に入れました。

app/views/recipe/shopping_list.html.erb
=> 買い物リストのviewをリファクタリングしました

app/controllers/recipe_controller.rb, app/views/recipe/pickup.html.erb, test/controllers/recipe_controller_test.rb
~~WIP = work in progress の Pull Requestです。
まだ実装中なのでレビューとマージをしないでください。~~
取り込むまでは終わったのでWIPをはずします。
このPull Requestで実装する内容
http://localhost:3000/pickup_recipe
にアクセスしたとき、材料リストに材料名と数量が表示されること。
=> add amount to pickup view

app/views/recipe/pickup.html.erb
~~WIP = work in progress の Pull Requestです。
まだ実装中なのでレビューとマージをしないでください。~~
ボタン追加は終わったのでWIPをはずします。
このPull Requestで実装する内容
http://localhost:3000/pickup_recipe
にアクセスしたとき、「チェンジ」ボタンが表示されること。
=> Add change button

README.md
次はテストカバレッジとか入れてみたいなーと考えていたりします。
参考にしたQiita
http://qiita.com/dtan4/items/13b0ea9edf5b99926446
=> Add build status and license image

app/controllers/recipe_controller.rb, app/views/recipe/shopping_list.html.erb
ショッピングリストに分量を追加しました。
確認よろしくお願いします。
=> Shopping list bind

app/controllers/recipe_controller.rb, app/models/recipe.rb, app/views/recipe/pickup.html.erb
以下を参考にして`recipe_index`をセッションに保存する実装に変更してみました。
- http://railsdoc.com/references/session
- http://ruby-rails.hatenadiary.com/entry/20141130/1417334030
`shopping_list`では、まずセッションから取得して、無ければランダムにしています。
=> recipe_index をセッションに保存するように変更

app/controllers/recipe_controller.rb
対応、できたと思います。
確認は http://localhost:3000/scrape でお願いします。
fixed #43
=> Repair get materialName

app/controllers/recipe_controller.rb, app/views/recipe/index.html.erb
テストページに中カテゴリー・小カテゴリーを確認するコードを追加しました。
=> 中カテゴリー・小カテゴリーを確認するためのサンプル

app/views/top/index.html.erb
トップの買い物ボタンを作成してみました。
一応それっぽいものはできましたが、コーディング規約は守れてないよう思います。
ご指摘お願い致します！
=> トップページの買い物リストボタンの作成

test/controllers/recipe_controller_test.rb
参考
https://blog.hello-world.jp.net/ruby/3127/
=> Cookie 保存のテスト追加

app/controllers/recipe_controller.rb, app/views/recipe/pickup.html.erb, config/routes.rb, test/controllers/recipe_controller_test.rb
データの持ち方（何をキーにするか？）や遷移など、いろいろ疑問はありますが、とりあえず Cookie に保存するところまで作ったので、あげておきます
参考
* http://railsdoc.com/references/cookies
=> Cookieへ買ったもの保存

app/views/layouts/application.html.erb
=> PuzzVege >> PuzzVeg

.travis.yml
=> Mod app endpoint

app/views/top/index.html.erb
マージ後に新しいendpointで変更を確認できるかのテスト
=> Confirm merge

app/assets/stylesheets/top.scss, app/views/top/index.html.erb
https://trello.com/c/maxty5p3
https://trello.com/c/p6kg3b6q
JavaScript で値を取得できるところまで確認できたので、いったんここまでとします。
データは、HTML5 カスタムデータ属性に入れています。
* 参考: http://dresscording.com/blog/html5/custom_data_attribute.html
続きはお願いしたいです。
=> ダミーのレシピデータ表示、野菜のデータ作成

README.md
=> ReadMe の Heroku URL を最新にする

app/controllers/top_controller.rb, app/views/top/start.html.erb, test/controllers/top_controller_test.rb
https://trello.com/c/GdAe4Bk3
- ボタンのみ配置してます
- 仮のキャッチフレーズを追加しました
=> 状態に応じてページを出しわける処理

app/controllers/top_controller.rb, app/views/application/_footer.html.erb, app/views/application/_header.html.erb, app/views/layouts/application.html.erb, app/views/top/start.html.erb, test/controllers/top_controller_test.rb
https://trello.com/c/YqWtKT0S
- ヘッダーを `_header.html.erb` 、フッターを `_footer.html.erb` に分けています
- `@no_header` 、`@no_footer` 変数で出し分けをしています
=> ヘッダ・フッタを未登録時Topでは出さないようにする

app/controllers/top_controller.rb, app/views/top/index.html.erb, test/controllers/top_controller_test.rb
https://trello.com/c/Yts6akDU
* DBから取得したデータのうち5件を画面に表示
=> DBから取得したレシピの画面への反映

app/views/top/index.html.erb
https://trello.com/c/EOih0PMP
まずここまでで、チェックボックス追加しただけです。
conflictしているので、修正コミットこの次に入れます。
=> Add checkbox

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/top.scss, app/views/top/index.html.erb
https://trello.com/c/MdWnxzk2
修正箇所は以下のとおり。
* `Chart.HorizontalBar` でエラーとなっていたので削除
*  `for-of` でエラーになっていたので、普通の for 文に変更
* `for-of` は、ECMAScript6 以降じゃないと使えない
* http://www.ituore.com/entry/javascript-for
* 「野菜登録する」ボタンが小さくなってしまうことがあるので、`font-size` で `calc` を使わないように修正
IE11 と Edge で確認。
=> IE でグラフが表示されるように修正

app/controllers/top_controller.rb, app/views/top/index.html.erb
19~21行目辺りの処理に今詰まってます、、、
手持ちの野菜の中から、０以外の物を取得して、レシピの中でその野菜が含まれているものを取得しようとしているのですが、モデル.find や　モデル.where辺りの使い方にはまってます
=> Search logic

app/views/top/index.html.erb
IEでも色が見えるようにしました。FFでも同様です。
こちらを参考にしています。
http://stackoverflow.com/questions/39332339/chartjs-canvas-not-displaying-rgba-colors-in-ie-safari-and-firefox
=> Fix graph coloring

app/views/top/index.html.erb
https://trello.com/c/GHTxsaoQ
- 初期状態ではチェックなし（＝使う予定のグラフはない状態）です
=> チェックボックスをチェックするとチャートに反映する

app/views/top/index.html.erb
=> IE で動作するように修正

app/views/top/index.html.erb
=> Fix table width

app/views/recipe/add_vegetables.html.erb
=> 野菜登録画面に個を付ける

app/views/top/index.html.erb
=> （グラフのあるページ）人数選択のプルダウン作成

app/assets/stylesheets/top.scss, app/views/top/index.html.erb
https://trello.com/c/FDRUZ2q6
表示がおかしかったので、直しました。
=> 野菜の数を一致させた時の表示が崩れているのを修正

app/assets/javascripts/dishes.coffee, app/views/recipe/add_vegetables.html.erb
plusボタンは表示はできたのですが、押しても数値に反映できていません。
どこを修正すればよいでしょうか？
=> 野菜登録ページに、野菜を1個刻みで追加するための＋ボタンを追加する
